# Generated by Django 5.2.1 on 2025-06-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftFlow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='actual_return',
            new_name='investment_return',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='expected_return',
        ),
    ]
