# Generated by Django 5.2.1 on 2025-06-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftFlow', '0002_rename_actual_return_investment_investment_return_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='investment_return',
            new_name='expected_return',
        ),
    ]
