# Generated by Django 5.2.1 on 2025-06-12 21:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftFlow', '0003_rename_investment_return_investment_expected_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='profit',
            old_name='amount_invested',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='saving',
            old_name='current_amount',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='income_growth',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='investment_gains',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='source',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='total_profit',
        ),
        migrations.RemoveField(
            model_name='profit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='saving_goal',
        ),
        migrations.RemoveField(
            model_name='saving',
            name='timeframe',
        ),
        migrations.AddField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profit',
            name='date_realized',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profit',
            name='investment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='ThriftFlow.investment'),
        ),
        migrations.AddField(
            model_name='saving',
            name='date_saved',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='saving',
            name='source_profit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ThriftFlow.profit'),
        ),
        migrations.AddField(
            model_name='saving',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
