# Generated by Django 5.2.1 on 2025-06-12 21:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftFlow', '0004_rename_amount_invested_profit_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saving',
            name='user',
            field=models.ForeignKey(default=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
