# Generated by Django 5.2.1 on 2025-06-12 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftFlow', '0006_alter_investment_user_alter_profit_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profits', to='ThriftFlow.investment'),
        ),
    ]
