# Generated by Django 5.2.1 on 2025-06-12 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftFlow', '0007_alter_profit_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThriftFlow.investment'),
        ),
    ]
