# Generated by Django 5.2.1 on 2025-06-12 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThriftFlow', '0008_alter_profit_investment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profit',
            name='date_realized',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profit',
            name='investment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profits', to='ThriftFlow.investment'),
        ),
        migrations.AlterField(
            model_name='saving',
            name='date_saved',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saving',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
